### PR TITLE
Fixes for JLFunction

### LINKED ISSUE #69: JLFunction does not support x -> x
Using `[6b7a57c9] Expronicon v0.10.3` on Julia 1.9.0, JLFunction cannot construct a function from an anonymous function with only one input. Somewhat strangely, `JLFunction(:((x, y) -> x))` does work.

```
julia> using Expronicon

julia> JLFunction(:(x -> x))
ERROR: MethodError: no method matching split_function_head(::Symbol; source::Nothing)

Closest candidates are:
  split_function_head(::Expr; source)
   @ Expronicon ~/.julia/packages/Expronicon/7EBrJ/src/analysis/split.jl:43

Stacktrace:
 [1] JLFunction(ex::Expr; source::Nothing)
   @ Expronicon ~/.julia/packages/Expronicon/7EBrJ/src/analysis/cons.jl:30
 [2] JLFunction(ex::Expr)
   @ Expronicon ~/.julia/packages/Expronicon/7EBrJ/src/analysis/cons.jl:16
 [3] top-level scope
   @ REPL[2]:1
```

This probably just needs `split_function_head` to have a new case for symbol, maybe.

### PR DESCRIPTION
**Pull request by 0x0f0f0f**
Fixes #69 and #72

### CODE REVIEW

File: src/analysis/split.jl [hunk 1]
```diff
@@ -52,15 +52,39 @@ function split_function_head(ex::Expr; source = nothing)
...
-        Expr(:(::), arg::Symbol, argtype) || Expr(:(::), argtype) => (nothing, Any[ex], nothing, nothing, nothing)
         Expr(:where, call, whereparams...) => begin
             name, args, kw, _, rettype = split_function_head(call)
             (name, args, kw, whereparams, rettype)
         end
         _ => throw(SyntaxError("expect a function head, got $ex", source))
     end
 end
-split_function_head(s::Symbol; source = nothing) = (nothing, Any[s], nothing, nothing, nothing)
+split_function_head(s::Symbol; source=nothing) = (nothing, Any[s], nothing, nothing, nothing)
```
Comment (Roger-luo) [inline src/analysis/split.jl:62]: can we also add some unit tests to cover these missing lines? not sure why this wasn't missing tho

**Review by Roger-luo — APPROVED** [review]

**Comment by Roger-luo** [comment]
Thanks! Great work!
